version: "3.8"

networks:
  proxy:
    name: proxy

services:
  mysql-db:
    image: mysql
    networks:
      - proxy
    ports:
      - 3305:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=conduit
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      retries: 3
  backend:
    build: ./backend
    networks:
      - proxy
    ports:
      - 8080:8080
    depends_on:
      mysql-db:
        condition: service_healthy
