name: Deploy

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remote connecting to server using SSH, then build and deploy the dockerize project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~/github/macamaca/macamaca-backend
            git pull origin main
            docker-compose stop
            docker-compose up -d --build
